# backend/Dockerfile
FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy the built JAR file into the container
COPY build/libs/*.jar app.jar

EXPOSE 5001

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]
