# Dockerfile.frontend
FROM node:18

# Install git
RUN apt-get update && apt-get install -y git

# Clone frontend repo
RUN git clone https://github.com/2300030174/cicd_project_frontend.git /app/frontend

WORKDIR /app/frontend

# Install dependencies
RUN npm install
RUN npm run build

# Expose port
EXPOSE 3000

CMD ["npm", "start"]
