# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clone frontend repo
      run: git clone https://github.com/2300030174/docker-ecommerce-frontend.git frontend
  
    - name: Checkout workflow repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker compose -f docker-compose.yml build
        docker compose -f docker-compose.yml push

    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        # Save SSH key locally
        echo "$EC2_SSH_KEY" > ec2_key.pem
        chmod 600 ec2_key.pem

        # SSH into EC2 and deploy
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          # Standard deployment folder
          DEPLOY_DIR=~/home_services

          # Create folder if it doesn't exist
          mkdir -p $DEPLOY_DIR
          cd $DEPLOY_DIR

          # Clone or pull latest workflow repo
          if [ ! -d ".git" ]; then
            git clone https://github.com/your-org/cicd_project_gitactions_aws.git .
          else
            git reset --hard
            git pull
          fi

          # Deploy using Docker Compose
          docker compose pull
          docker compose up -d
        EOF

